language: erlang

matrix:
  include:
    - otp_release: 22.0.5
    - otp_release: 21.3.8

before_script:
  - chmod +x bootstrap_travis.sh
  - ./bootstrap_travis.sh
script:
  - rebar3 ct --cover
  - rebar3 eunit --cover
  - rebar3 cover -v
