language: erlang

matrix:
  include:
    - otp_release: 23.0-rc2
    - otp_release: 22.3.0
    - otp_release: 21.3.8

before_script:
  - "chmod +x bootstrap_travis.sh"
  - "./bootstrap_travis.sh"
script:
  - "make coverage"
