version: '3.7'

x-defaults: &defaults
  image: sentry:9.1-onbuild
  restart: unless-stopped
  depends_on:
    - sentry-redis
    - sentry-postgres
    - sentry-memcached
  env_file: .env
  environment:
    SENTRY_MEMCACHED_HOST: sentry-memcached
    SENTRY_REDIS_HOST: sentry-redis
    SENTRY_POSTGRES_HOST: sentry-postgres
  volumes:
    - sentry-data:/var/lib/sentry/files

services:
  workspace:
    build:
      context: .
      args:
        PUID: ${PUID}
        PGID: ${PGID}
    restart: unless-stopped
    init: true
    command: sleep infinity
    volumes:
      - .:/workspace

  sentry:
    <<: *defaults
    ports:
      - "$SENTRY_WEB_PORT:9000"

  sentry-cron:
    <<: *defaults
    command: run cron

  sentry-worker:
    <<: *defaults
    command: run worker

  sentry-memcached:
    restart: unless-stopped
    image: memcached:1.5-alpine

  sentry-redis:
    restart: unless-stopped
    image: redis:3.2-alpine

  sentry-postgres:
    restart: unless-stopped
    image: postgres:9.5
    volumes:
      - sentry-postgres:/var/lib/postgresql/data

volumes:
  sentry-data:
  sentry-postgres:
